### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by RichardWinters** [khtao/Microsoft-Rewards#1]
可以详细说说怎么用吗？

**Comment by khtao** [comment]
已更新readme文件，请参考

**Comment by khtao** [comment]
> 可以详细说说怎么用吗？
已更新readme文件，请参考

**Comment by RichardWinters** [comment]
> > 可以详细说说怎么用吗？
> > 已更新readme文件，请参考

这么快回复，感谢！
在电脑上安装python, 2.X还是3.x呢？

**Comment by khtao** [comment]
> > > 可以详细说说怎么用吗？
> > > 已更新readme文件，请参考
> 
> 这么快回复，感谢！ 在电脑上安装python, 2.X还是3.x呢？

自然是python 3.x啦
